// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwIoxjA4IusI_kHiSFg7epMhoR-jzET3Y',
    appId: '1:384737848388:web:15fb9ecafdc7c2fad8e011',
    messagingSenderId: '384737848388',
    projectId: 'smart-chair-ee4e3',
    authDomain: 'smart-chair-ee4e3.firebaseapp.com',
    storageBucket: 'smart-chair-ee4e3.firebasestorage.app',
    measurementId: 'G-JJ1K85S3RS',
    databaseURL: 'https://smart-chair-ee4e3-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwIoxjA4IusI_kHiSFg7epMhoR-jzET3Y',
    appId: '1:384737848388:web:4f14faa34850d564d8e011',
    messagingSenderId: '384737848388',
    projectId: 'smart-chair-ee4e3',
    authDomain: 'smart-chair-ee4e3.firebaseapp.com',
    storageBucket: 'smart-chair-ee4e3.firebasestorage.app',
    measurementId: 'G-S0XP3FS86H',
  );
}
